Сделал вторую лабу. Было больно.
dbondin/am16-ds pull request #35
Opened 2018-02-14 18:07 UTC by CandyJunkie

2018-02-14 18:08 UTC, CandyJunkie commented
Для тех кто читает, не повторяйте моих ошибок и не считайте дисперсию. :)

2018-02-15 07:40 UTC, dbondin requested changes
Мне не нравится, что весь файл целиком читается в память. Так нельзя.

Остальные каменты - не принципиальные

2018-02-15 07:40 UTC, dbondin commented on labs/lab2/CandyJunkie/lab2.cpp
> +	//system ("chcp 1251"); // включаем для отладки в винде.
#ifdef _WIN32
system("chcp 1251")
#endif // _WIN32 И не надо никаких туда-сюда коментариев

2018-02-15 07:40 UTC, dbondin commented on labs/lab2/CandyJunkie/lab2.cpp
> +		return 1;
Назачем int? Ну почему не сделать enum с нормальными говорящими названиями. 
Ведь потом фиг поймешь, что такое 1 и что такое 2

2018-02-15 07:40 UTC, dbondin commented on labs/lab2/CandyJunkie/lab2.cpp
> +	for (int i = 0; i < 256; ++i) {
Правда-же всю эту ерунду с заполнением табличек можно сделать один раз во-вспомогательной программке, которая все заполнит и сгенерит какой-нибудь codes.h со всеми этими массивами уже заполненными.
Зачем при каждом запуске это все колдовать?

2018-02-15 07:40 UTC, dbondin commented on labs/lab2/CandyJunkie/lab2.cpp
> +	while (text.get (c)) {
Эээээ.... весь файл читаем в std::string ? Целиком?
А если это полное собрание сочинений графа Толстого?

2018-02-15 11:05 UTC, CandyJunkie commented
По всем пунктам исправил.

2018-02-16 07:32 UTC, dbondin approved these changes

2018-02-16 07:32 UTC, merged