Вторая лабораторная
dbondin/am16-ds pull request #36
Opened 2018-02-14 22:51 UTC by NeoZet

Можно задать входной и выходной файлы аргументами командной строки (./lab2 in out)
Если задать только вхдной (./lab2 in) то выходной будет задан по умолчанию
Можно запустить без аргументов, тогда будет предложено ввести входной файл

2018-02-15 07:48 UTC, dbondin requested changes

2018-02-15 07:48 UTC, dbondin commented on labs/lab2/NeoZet/lab2.c
> +        text[p] = getc(ftxt);
Весь файл в память? Рили?
Ведь я найду книжку, которая в пямять не влезет, правда-же?

2018-02-15 07:48 UTC, dbondin commented on labs/lab2/NeoZet/lab2.c
> +        for(j=0; j<64; ++j)
Для каждой буковки свой цикл на 64 итерации?
Это-ж застрелиться.
Избавьтесь от внутреннего цикла.

2018-02-15 12:21 UTC, NeoZet commented on labs/lab2/NeoZet/lab2.c
> +        for(j=0; j<64; ++j)
Но ведь 64 итерации выполнется только для последнего символа, потому что как только мы натыкаемся на нужный символ выполняется break. (Символы в массивах упорядочены по средней частоте появления в осмысленном тексте от самого часто встречающегося к самому редкому). 
Как уйти от вложенного цикла без полной переработки алгоритма я не знаю, разве что переходить в С++ и использовать контейнеры или алгоритмы.

Или есть вариант как просто уменьшить количество итераций:
Если нам попадается НЕ символ кириллицы, то просто его не прогонять по массиву(мой косяк то что сразу так не сделал) и тогда среднее количество итераций будет ~25-30.
Такой вариант приемлем?

2018-02-15 12:41 UTC, NeoZet commented
Теперь данные считываются кусками, пока не кончится файл
Вместо ухода от вложенного цикла снизил количество итераций (причину и способ, как это сделал изложил в комментарии к первому реквесту)

2018-02-16 16:01 UTC, dbondin approved these changes

2018-02-16 16:01 UTC, dbondin commented on labs/lab2/NeoZet/lab2.c
> +        int lenOfText = strlen(text);
Здесь потенциально ошибка.
Лучше считать кол-во прочитанных символов в предыдущем цикле явным образом.
А так вы завязываетесь на то, что в файле гарантированно нет нулевых байт - зачем такие ограничения искусственные?

2018-02-16 16:09 UTC, NeoZet commented
Т.е. можно просто использовать итеририрующую перенную цикла?

2018-02-16 16:12 UTC, merged