Третья лабораторная.
dbondin/am16-ds pull request #37
Opened 2018-02-15 10:35 UTC by moisus

2018-02-16 10:38 UTC, dbondin requested changes
А чего все файлы в корень? Все файлы надо в папочки выкладывать, labs/labN/login/

2018-02-16 10:38 UTC, dbondin commented on calc.h
> +        return false;
А если stack<string> сделать, то что такое return false будет?

2018-02-17 09:36 UTC, moisus commented
fix

2018-02-19 14:28 UTC, dbondin approved these changes

2018-02-19 14:28 UTC, merged