lab2
dbondin/am16-ds pull request #43
Opened 2018-02-18 07:06 UTC by Deuteriy

2018-02-19 14:35 UTC, dbondin requested changes

2018-02-19 14:35 UTC, dbondin commented on labs/lab2/deuteriy/mylab2.c
> +		for(j=0; j<sizeof(unk_text)-1; ++j)
Что, весь файл прочитаем в память? А если он большой? А если он не файл - а нескончаемый поток данных - лента из твиттера постоянно выдающая новые данные?
Ведь не надо все в память влущать, чтобы все это работало.

Для первой части (определить кто куда откуда) - можно и в память, но не весь файл, а килобайт-два - этого достаточно для сбора статистики и анализа кодировки.

А уже реальное перекодирование всего файла - зачем в пямять? Прочитал байт - перекодировал - записал, и так пока in не закончится.

2018-02-20 09:22 UTC, Deuteriy commented
Почему весь файл? 5000 символов(можно меньше, просто чтобы наверняка). Эти 5000 символов в память, их выводит в txt. Потом заменяем значения памяти и выводим опять(Прогоняем еще раз по алгоритму). Изменил с 5000 на 1000 и понял одну ошибку, что при такой выдаче, когда заменяем значения в массиве, остаются ненужные элементы с предыдущего шага. Теперь я их зануляю.

2018-02-20 12:00 UTC, dbondin requested changes

2018-02-20 12:00 UTC, dbondin commented on labs/lab2/deuteriy/mylab2.c
> +		if(decode(unk_text, utf, complexity))
Но теперь 1000 байт не только при детекте, но и при реальном перекодировании получается?
Или я где-то что-то пропустил в логике кода тут?

2018-02-20 12:29 UTC, Deuteriy commented
> "Что, весь файл прочитаем в память? А если он большой? А если он не файл - а нескончаемый поток данных - лента из твиттера постоянно выдающая новые данные? Ведь не надо все в память влущать, чтобы все это работало."
Я думал проблема в том что весь файл в памяти. Но он не весь в памяти, а только его часть

2018-02-20 12:56 UTC, Deuteriy commented
Если брать по одному символу, то у меня возникает проблема в детекте более глубокого уровня, так как я перекодирываю только символы, а чтобы выяснить что за кодировка далее мне нужен текст. Слишком глобальные изменения тогда нужны будут. Память на 1000 символов компьютер посилен выделить, поэтому можно оставить так?

2018-02-20 14:56 UTC, dbondin commented
>> Если брать по одному символу, то у меня возникает проблема в детекте более глубокого уровня
Вот для детекта - надо 1000 (или 5000) символов - это нормально как раз

А вот когда уже поняли как оно закодировано - надо-же весь файл прогнать по этим перекодировкам, а не только первые 1000 букв, разве нет? Вот тут как-раз по-одному, ничего в память в больших обьемах не надо читать

2018-02-20 16:00 UTC, Deuteriy commented
У меня нигде не сохраняется путь детектеда, он совмещен вместе с перекодировкой.
Проходят не только 1000 букв, а весь файл кусками по 1000

2018-02-22 05:00 UTC, Deuteriy commented
Еще загрузил 3 лабу

2018-02-22 11:35 UTC, dbondin approved these changes

2018-02-22 11:35 UTC, merged