Лаба 3
dbondin/am16-ds pull request #44
Opened 2018-02-18 18:17 UTC by bomgenka

Не обращайте внимание на коменты и странные названия.

2018-02-19 14:40 UTC, dbondin commented
Зачем Laba3.exe сюда?
Сюда только исходники

2018-02-19 14:44 UTC, dbondin commented
Не вижу изменений в корневом README.md

2018-02-19 14:45 UTC, dbondin requested changes
Каменты

2018-02-20 11:56 UTC, dbondin requested changes

2018-02-20 11:56 UTC, dbondin commented on README.md
> +| 2   | Шантин Максим @sharok007            | 2     | 2     | 1     |       |       |       |       |
ээээээ..... а что тут за куча изменений?

2018-02-20 12:54 UTC, bomgenka commented on README.md
> +| 2   | Шантин Максим @sharok007            | 2     | 2     | 1     |       |       |       |       |
Я это тоже увидел, но когда открываю файл у себя, то у меня все в порядке.

2018-02-20 14:46 UTC, dbondin commented on README.md
> +| 2   | Шантин Максим @sharok007            | 2     | 2     | 1     |       |       |       |       |
ок. бывает

2018-02-20 14:51 UTC, dbondin approved these changes

2018-02-20 14:51 UTC, dbondin commented on README.md
> +| 2   | Шантин Максим @sharok007            | 2     | 2     | 1     |       |       |       |       |
Нет, а как я это мержить буду ...

2018-02-20 14:51 UTC, merged